apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  workspaces:
  - name: gitrepos
    description: The git repo will be cloned onto the volume backing this workspace
  - name: config
  results:
  - name: image
    description: The image+tag that was created
  params:
  - name: PATH_CONTEXT
    default: backend
    description: The location of the path to run s2i from.
    type: string
  - name: TLSVERIFY
    default: "true"
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    type: string
  - name: subdirectory
    default: "dev"
    description: subdirectory in the gitrepos workspace where the dev repo has been cloned to
    type: string
  - name: OUTPUT_IMAGE
    type: string
  - name: TAG
    default: latest 
    type: string
  - name: DOCKERFILE
    default: Dockerfile
    type: string
  steps:
  - name: build
    image: quay.io/buildah/stable:v1.11.0
    script: |
      cd $(params.PATH_CONTEXT)
      buildah bud --tls-verify=$(params.TLSVERIFY) --layers -f $(params.DOCKERFILE) -t $(params.OUTPUT_IMAGE) .
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: $(workspaces.gitrepos.path)/$(params.subdirectory)
  - name: push
    image: quay.io/buildah/stable:v1.11.0
    script: |
      buildah push --tls-verify=$(params.TLSVERIFY) $(params.OUTPUT_IMAGE) docker://$(params.OUTPUT_IMAGE):$(params.TAG)
      echo -n "$(params.OUTPUT_IMAGE):$(params.TAG)" >$(results.image.path)
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers