apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy
spec:
  workspaces:
  - name: config
    description: configmap contents
  - name: quay-secret
    description: push secret for quay.io
  params:
  - name: TAG
    type: string
  - name: SOURCE_IMAGE
    type: string
  - name: TARGET_IMAGE_CONFIGMAPKEY
    type: string
  steps:
  - name: skopeo-copy
    image: quay.io/redhat-emea-ssa-team/skopeo-ubi:latest
    script: |
      skopeo copy --authfile=$(workspaces.quay-secret.path)/.dockerconfigjson --src-tls-verify=false --dest-tls-verify=false docker://$(params.SOURCE_IMAGE):$(params.TAG) docker://$(cat $(workspaces.config.path)/$(params.TARGET_IMAGE_CONFIGMAPKEY)):$(params.TAG)