apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helloworld-unittest
spec:
  workspaces:
  - name: gitrepos
    description: The git repo will be cloned onto the volume backing this workspace
  params:
  - name: subdirectory
    description: subdirectory inside the "gitrepos" workspace to clone the git repo into
    type: string
    default: ""
  - name: PATH_CONTEXT
    description: defines the path where to run unittest
    type: string
  steps:
  - name: run-unittest
    image: frolvlad/alpine-python3
    script: |
      pip install Flask
      cd $(workspaces.gitrepos.path)/$(params.subdirectory)/$(params.PATH_CONTEXT)
      python3 -m unittest tests/unittest/test_app.py
    workingDir: $(workspaces.gitrepos.path)/$(params.subdirectory)